spring:
  application:
    name: item-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:20011/eureka,http://eureka2:20012/eureka

      
---
spring:
  profiles: item1

server:
  port: 8001     
  
---
spring:
  profiles: item2

server:
  port: 8002